### PR TITLE
Feature/rework globals section

### PR DESCRIPTION
**Pull request by saltcod**

### CODE REVIEW

**Comment by saltcod** [comment]
The website's repo doesnt have Issues enabled it seems, so we can have the discussion here if you'd like. 

I've moved the global parameters section to the sidebar on appropriate pages, thusly:
https://dl.dropboxusercontent.com/s/4h7mduh4v9mw517/2015-09-10%20at%2011.41%20AM.png

To determine "appropriate" pages, I had to add a body class function to the header template.  I excluded the sidebar from the homepage, the blog page, and the configuration page.  The one left to do is exclude from single blog post pages. I'm working on that at the moment.

**Comment by danielbachhuber** [comment]
Ok. Are you aware the globals documentation needs to be created as a part of the build process?

When you run `vendor/bin/phake` right now, some of your changes will be overwritten by the build process.

We'll need to make sure to update the build process to output globals in this manner.

**Comment by saltcod** [comment]
That's what I was kinda thinking, but I thought I'd go ahead and hardcode for the moment.  If/when you're ok with the layout changes, I can look at how to wire this up properly.

**Comment by danielbachhuber** [comment]
Sounds good.

**Comment by danielbachhuber** [comment]
@saltcod how's this coming along?

**Comment by danielbachhuber** [comment]
Picked things over into #86

Thanks again for your styles, @saltcod

**Pull request closed without merging**
